---
- name: Optimize Linux System Performance
  hosts: all
  become: yes

  vars:
    fstab_backup: "/etc/fstab.bak"
    fstab_file: "/etc/fstab"
    sysctl_file: "/etc/sysctl.conf"

  tasks:

  - name: Backup /etc/fstab
    copy:
      src: "{{ fstab_file }}"
      dest: "{{ fstab_backup }}"
      backup: yes

  - name: Replace relatime with noatime,data=writeback in fstab
    replace:
      path: "{{ fstab_file }}"
      regexp: 'defaults,relatime'
      replace: 'defaults,noatime,data=writeback'

  - name: Remount root filesystem
    command: mount -o remount /
    notify: reload_systemd

  - name: Install required packages
    apt:
      name:
        - cpufrequtils
        - sysstat
        - iotop
        - lm-sensors
        - zram-tools
      state: present
      update_cache: yes

  - name: Set CPU governor to performance
    command: cpufreq-set -r -g performance

  - name: Enable and start fstrim.timer
    systemd:
      name: fstrim.timer
      enabled: yes
      state: started

  - name: Run immediate TRIM
    command: fstrim -av

  - name: Configure sysctl performance parameters
    blockinfile:
      path: "{{ sysctl_file }}"
      block: |
        # Performance Optimizations
        vm.swappiness=10
        vm.dirty_ratio=20
        vm.dirty_background_ratio=10
        fs.file-max = 2097152
        net.ipv4.tcp_fin_timeout = 10
        net.ipv4.tcp_tw_reuse = 1
        net.core.rmem_max = 16777216
        net.core.wmem_max = 16777216
        net.core.somaxconn = 4096
        net.ipv4.ip_local_port_range = 10240 65535

  - name: Apply sysctl changes
    command: sysctl -p

  - name: Vacuum systemd journal logs to 500M
    command: journalctl --vacuum-size=500M

  - name: Disable NetworkManager-wait-online.service
    systemd:
      name: NetworkManager-wait-online.service
      enabled: no
      state: stopped

  - name: Disable VirtualBox services if present
    systemd:
      name: "{{ item }}"
      enabled: no
      state: stopped
    loop:
      - vboxdrv.service
      - vboxweb-service.service
      - vboxballoonctrl-service.service
      - vboxautostart-service.service
    ignore_errors: yes

  - name: Disable ModemManager if not needed
    systemd:
      name: ModemManager.service
      enabled: no
      state: stopped
    ignore_errors: yes

  handlers:
    - name: reload_systemd
      command: systemctl daemon-reload

