---
dependency: []
galaxy_info:
  author: your_name
  description: Role for auto-cpufreq management
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
# Add more metadata as needed
